### ISSUE TITLE
Listagem e cadastro de Categoria de Ocorrência

### ISSUE THREAD

**Issue by senegoid** [deltasge/roadmap#10]

**Comment by ricardotizatto** [comment]
Feito o teste de Adicionar, alterar, excluir e pesquisar uma categoria de ocorrências na tela de Categoria de Ocorrências 
e visto que está funcionando perfeitamente todas as ações.

![imagem_2021-06-15_114001](https://user-images.githubusercontent.com/6655307/122072670-2d2fda80-cdce-11eb-8b95-e130735829b8.png)
