### ISSUE TITLE
Cadastro do cliente Delta (atual Escola) e configurações gerais.

### ISSUE THREAD

**Issue by senegoid** [deltasge/roadmap#102]

**Comment by senegoid** [comment]
https://github.com/deltasge/voldemort/pull/29

**Comment by ricardotizatto** [comment]
Feito o teste de Adicionar, alterar, excluir e pesquisar um tipo de ocorrência na tela de Empresas e visto que está funcionando perfeitamente todas as ações.

![image](https://user-images.githubusercontent.com/6655307/125451440-aee79eee-e7c9-4d46-9f84-1e342b590f5b.png)
