### ISSUE TITLE
Listagem e cadastro de Funcionário

### ISSUE THREAD

**Issue by senegoid** [deltasge/roadmap#11]

**Comment by ricardotizatto** [comment]
Feito o teste de Adicionar, alterar, excluir e pesquisar um funcionário na tela de Funcionário e visto que está funcionando perfeitamente todas as ações.

![imagem_2021-06-15_114331](https://user-images.githubusercontent.com/6655307/122073244-aa5b4f80-cdce-11eb-9521-bfc4f79c5207.png)
