### ISSUE TITLE
Listagem e cadastro de Cliente

### ISSUE THREAD

**Issue by senegoid** [deltasge/roadmap#2]

**Comment by ricardotizatto** [comment]
Feito o teste de Adicionar, alterar, excluir e pesquisar um cliente tela de Clientes 
e visto que está funcionando perfeitamente todas as ações.

![imagem_2021-06-15_114514](https://user-images.githubusercontent.com/6655307/122073585-e7274680-cdce-11eb-8480-218e035640d8.png)
