### ISSUE TITLE
Listagem e cadastro de Usuário

### ISSUE THREAD

**Issue by senegoid** [deltasge/roadmap#3]

**Comment by ricardotizatto** [comment]
Feito o teste de Adicionar, alterar, excluir e pesquisar um usuário na tela de usuários e visto que está funcionando perfeitamente todas as ações.

![imagem_2021-06-15_111950](https://user-images.githubusercontent.com/6655307/122069186-5b5feb00-cdcb-11eb-999d-7f4f739901e4.png)
