### ISSUE TITLE
Listagem e cadastro de Feriado

### ISSUE THREAD

**Issue by senegoid** [deltasge/roadmap#4]

**Comment by ricardotizatto** [comment]
Feito o teste de Adicionar, alterar, excluir e pesquisar um ano tela de Feriados e visto que está funcionando perfeitamente todas as ações.

![imagem_2021-06-15_112331](https://user-images.githubusercontent.com/6655307/122069839-df19d780-cdcb-11eb-95fe-5bfa049783bc.png)
