### ISSUE TITLE
Listagem e cadastro de Legenda

### ISSUE THREAD

**Issue by senegoid** [deltasge/roadmap#5]

**Comment by ricardotizatto** [comment]
Feito o teste de Adicionar, alterar, excluir e pesquisar uma legenda na tela de legenda e visto que está funcionando perfeitamente todas as ações.

![imagem_2021-06-15_112545](https://user-images.githubusercontent.com/6655307/122070253-2e600800-cdcc-11eb-8eac-01cdf4282bf4.png)
