### ISSUE TITLE
Listagem e cadastro de Empresa

### ISSUE THREAD

**Issue by senegoid** [deltasge/roadmap#6]

**Comment by ricardotizatto** [comment]
Feito o teste de Adicionar, alterar, excluir e pesquisar uma empresa na tela de empresas e visto que está funcionando perfeitamente todas as ações.

![imagem_2021-06-15_113033](https://user-images.githubusercontent.com/6655307/122071113-daa1ee80-cdcc-11eb-9148-ca9e01cb70e4.png)
