### ISSUE TITLE
Listagem e cadastro de Curso

### ISSUE THREAD

**Issue by senegoid** [deltasge/roadmap#7]

**Comment by ricardotizatto** [comment]
Feito o teste de Adicionar, alterar, excluir e pesquisar um curso na tela de cursos e visto que está funcionando perfeitamente todas as ações.

![imagem_2021-06-15_113332](https://user-images.githubusercontent.com/6655307/122071621-45532a00-cdcd-11eb-9d2a-82c50cfdd81d.png)
