### ISSUE TITLE
Listagem e cadastro de Matéria

### ISSUE THREAD

**Issue by senegoid** [deltasge/roadmap#8]

**Comment by ricardotizatto** [comment]
Feito o teste de Adicionar, alterar, excluir e pesquisar uma matéria na tela de Materiais e visto que está funcionando perfeitamente todas as ações.
![imagem_2021-06-15_113634](https://user-images.githubusercontent.com/6655307/122072133-b1359280-cdcd-11eb-8170-9300ad8dcaeb.png)
