### ISSUE TITLE
Listagem e cadastro de Tipo de Ocorrência

### ISSUE THREAD

**Issue by senegoid** [deltasge/roadmap#9]

**Comment by ricardotizatto** [comment]
Feito o teste de Adicionar, alterar, excluir e pesquisar um tipo de ocorrência  na tela de Tipo Ocorrência e visto que está funcionando perfeitamente todas as ações.

![imagem_2021-06-15_113837](https://user-images.githubusercontent.com/6655307/122072469-fa85e200-cdcd-11eb-87db-be39db4a20e8.png)
